Documentation:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: semantic
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent
Style/IndentHash:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '[]'
    '%w': '[]'
    '%W': '[]'
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/EndAlignment:
  AlignWith: variable
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Metrics/ClassLength:
  Max: 150
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 40